 name: DEV Deploy
 on:
      workflow_dispatch:
 jobs:
    
      deploy:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v2
    
          - name: master
    
            uses: appleboy/ssh-action@master
    
            with:
              host: 157.245.109.240
              username: root
              password: M<zWH9ygM%8}k5kv
    
              script: |
                cd /var/www/html/hire-nanny
                
                php artisan down
                
                git checkout -f
                git branch -u origin/master
                git pull
                
                composer install --optimize-autoloader --no-dev
                
                npm install
                npm update
                npm run production
                
                php artisan cache:clear
                php artisan view:clear
                php artisan config:cache
                php artisan up
