name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run production
    - name: Commit built assets
      run: |
        git config --local user.email "mgupta@mind-roots.com"
        git config --local user.name "mindrootstech"
        git checkout -B deploy
        git add -f public/
        git commit -m "Build front-end assets"
        git push -f origin deploy
    - name: Safehire
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 157.245.109.240
        password: M<zWH9ygM%8}k5kv
        script: 'cd /var/www/html/nanny'
