name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: "root"
          host: "157.245.109.240"
          password: "M<zWH9ygM%8}k5kv"
          script: 'RUN_YPUR_DEPLOYMENT_SCRIPT' #cd /var/www/html/hire-nanny && ./server_deploy.sh
